### ISSUE TITLE
Allow read requests without validation

### ISSUE THREAD

**Issue by danyalutsevich** [eicrud/eicrud#63]
I'd love to have cruds out of the box without need to add some CMD, DTO or any additional code.
Right now every read request validates before execution.
I'd love to have an option to disable validation.

- Possibe solutions:

1. Provide an option to define new dto for read operations ([nestjsx/crud example](https://gid-oss.github.io/dataui-nestjs-crud/controllers/#dto))
It can be done in a similar approach like in @nestjs/mapped-types
Some function that will remove validation decorators in the entity or 
change it to IsObject decorators with allowed operations.
For example $eq, $like, $not etc. You will be able to define your own.

2. Add option that will disable validation for the request as @acrosett proposed
As @acrosett said disabling validation for read requests can lead to ReDoS attack
May be adding a timeout and rate limiting will solve this problem?

Personaly ReDoS is not a problem for me I'd love to accept the risk and use read requests without validation
And also regex in request is not important for me. $like is enough for my purposes

**Comment by acrosett** [comment]
As discussed, you can also access [mikro-orm's query conditions](https://mikro-orm.io/docs/query-conditions) by creating a [search command](https://docs.eicrud.com/recipes/search-command/), that would be the new DTO for read operations.

Generally speaking not validating reads may open DDOS attack vectors via expensive queries (I'm not sure about the $and & $or operators for example). But I agree that query validation can be overkill for some applications.

The simplest solution would be to add a `skipQueryValidationForRoles` field to the services' security (with inheritance).

For example `skipQueryValidationForRoles: ["user"]` would disable validation for read and update queries (for all roles that inherit `user`).

**Comment by acrosett** [comment]
Let's note that the `$or` & `$and` operators allow bypassing negative rules.

For example: 
```
cannot('read', 'entity', { visibility: 'private' })
```
would not block the query:
```
{ $or: [{  visibility: 'private' }] }
```
Even though you don't usually guard reads with negative rules
