### ISSUE TITLE
Bug: Module not found its corresponding type declarations.

### ISSUE THREAD

**Issue by Rahulkanyalgith** [eicrud/eicrud#83]
**Describe the bug**
Cannot find module "../test_exports/services/user-profile"
 or its corresponding type declarations.

** test_exports is not found ..

it found in many lines like..
import { SuperclientTest as ExportedSuperclientTest } from '../test_exports/services/superclient-ms/superclient-test/superclient-test.entity';
import { DragonFruit as ExportedDragonFruit } from '../test_exports/services/dragon-fruit/dragon-fruit.entity'

**Comment by acrosett** [comment]
It seems you are trying to contribute to Eicrud, in that case, you need to run `npm run setup:tests` as specified in the [contributing guide](https://github.com/eicrud/eicrud/blob/develop/CONTRIBUTING.md). 

If you are trying to use the framework, there is no need to clone the repo, you can follow the [documentation](https://docs.eicrud.com/installation/) to create a new project

**Comment by Rahulkanyalgith** [comment]
Ok i will try to run npm run setup:tests .thanks for helping @acrosett
